site_name: Personal blog
site_description: My personal blog to keep track of my thoughts and ideas.
site_url: https://cstalhem.github.io

theme:
  name: material
  features:
    - navigation.path
    - navigation.prune
  icon:
    repo: fontawesome/brands/git-alt
  repo_url: https://github.com/cstalhem/cstalhem.github.io
  repo_name: cstalhem/cstalhem.github.io

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.betterem

plugins:
  - search
  - blog:
      blog_dir: .
      categories_allowed:
        - blogging
        - projects
        - homelab
        - coding
      post_date_format: long
      post_excerpt_separator: <!-- end-excerpt -->
      archive_url_date_format: yyyy/MM
  - meta
  - tags
