backend:
  name: github
  repo: cstalhem/cstalhem.github.io
  branch: main
  use_graphql: true
  base_url: https://sveltia-cms-auth.carl-649.workers.dev/

# These settings are required for Decap CMS to work properly
site_url: https://cstalhem.github.io
display_url: https://cstalhem.github.io

media_folder: static/images
public_folder: /images

locale: en
search: false
slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: posts
    label: Blog Posts
    label_singular: Post
    create: true
    folder: content/posts
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    summary: "{{title}}\n{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - {
          label: "Categories",
          name: "categories",
          widget: "relation",
          collection: "categories",
          search_fields: [name],
          value_field: name,
          display_fields: [name],
          required: true,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "relation",
          collection: "tags",
          search_fields: [name],
          value_field: "name",
          display_fields: ["name"],
          multiple: true,
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          modes: [raw, rich_text],
          required: true,
        }
  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    create: true
    folder: content/tags
    path: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    create: true
    folder: content/categories
    path: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
