backend:
  name: github
  repo: cstalhem/cstalhem.github.io
  branch: main
  use_graphql: true
  base_url: https://sveltia-cms-auth.carl-649.workers.dev/

# These settings are required for Decap CMS to work properly
site_url: https://cstalhem.github.io
display_url: https://cstalhem.github.io

media_folder: static/images
public_folder: /images

locale: en
search: false
slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: posts
    label: Blog Posts
    label_singular: Post
    create: true
    folder: content/posts
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    summary: "{{year}}-{{month}}-{{day}} - {{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          default: "{{now}}",
          format: "YYYY-MM-DDTHH:mm:ss",
          picker_utc: false,
          required: true,
        }
      - { label: "Summary", name: "summary", widget: "string", required: false }
      - {
          label: "toc",
          name: "toc",
          widget: "boolean",
          default: true,
          required: false,
        }
      - {
          label: "Read time",
          name: "readTime",
          widget: "boolean",
          default: true,
          required: false,
        }
      - {
          label: "Auto Number",
          name: "autonumber",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Hide Back to top button",
          name: "hideBackToTop",
          widget: "hidden",
          default: false,
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "relation",
          collection: "categories",
          search_fields: ["title"],
          value_field: "title",
          display_fields: ["title"],
          required: true,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "relation",
          collection: "tags",
          search_fields: ["title"],
          value_field: "title",
          display_fields: ["title"],
          multiple: true,
          required: false,
        }
      - {
          label: "Show tags",
          name: "showTags",
          widget: "boolean",
          default: true,
          required: false,
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          modes: [raw, rich_text],
          required: true,
        }
  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    create: true
    folder: content/tags
    path: "{{title}}/_index"
    fields:
      - { label: "Name", name: "title", widget: "string" }
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    create: true
    folder: content/categories
    path: "{{title}}/_index"
    fields:
      - { label: "Name", name: "title", widget: "string" }
